### PR TITLE
Add Pyto

### PR DESCRIPTION
**Pull request by ColdGrub1384**
https://pyto.app

### CODE REVIEW

**Comment by pietropizzi** [comment]
Thanks for the addition. Could you maybe add the icon of the app as well as described in https://github.com/pietropizzi/app-talk/blob/master/CONTRIBUTING.md#good-to-know?

**Comment by ColdGrub1384** [comment]
I just added it. Thanks

**Comment by pietropizzi** [comment]
I just saw that the workflow I linked to can't be imported to the Shortcuts app so I made a new one: https://www.icloud.com/shortcuts/e0ec4c870d10481d82e953db7ee8e6be

Please use it because it produces an image that is not a square but rounded.

Thanks

**Comment by ColdGrub1384** [comment]
Oh sorry, I just added the updated icon. Thank you

**Comment by pietropizzi** [comment]
Perfect! Thanks for the contribution!

**Pull request merged**
